from datetime import datetime
# -*- coding: utf-8 -*-

db.define_table('Pasantia',
    Field('titulo',
           label='Titulo'),
    Field('estudiante','reference Estudiante',
          requires=IS_IN_DB(db, db.Estudiante, '%(carnet)s',error_message='Elija uno de los estudiantes.'),
          label='Estudiante (*)'),
    Field('tutor_academico','reference Profesor',
          requires=IS_IN_DB(db, db.Profesor, '%(usuario)s',
          error_message='Elija un tutor.'),
          label='Tutor Academico (*)'),
    Field('tutor_industrial','reference Tutor_Industrial',
          requires=IS_IN_DB(db, db.Tutor_Industrial, '%(apellido)s',
          error_message='Elija un tutor.'),
          label='Tutor Industrial (*)'),
    Field('periodo','reference Periodo',
          requires=IS_IN_DB(db, db.Periodo, '%(mes_inicio)s-%(mes_final)s',
          error_message='Elija un periodos.'),
          label='Periodo (*)'),
    Field('area_proyecto','reference Area_Proyecto',
          requires=IS_IN_DB(db, db.Area_Proyecto, '%(nombre)s',
          error_message='Elija una de las áreas de proyecto'),
          label='Areas de Proyectos (*)'),
    Field('resumen_proyecto','text',
          label ='Resumen del Proyecto',
          represent=lambda v, r: 'N/A' if v is None else v),
    Field('materia','reference Materia',
          requires=IS_IN_DB(db, db.Materia, '%(codigo)s',
          error_message='Elija una de las materias.'),
          label='Materia (*)'),
    Field('objetivo',
          label ='Objetivo General',
          represent=lambda v, r: 'N/A' if v is None else v),
    Field('confidencialidad',
          requires=[IS_NOT_EMPTY
                        (error_message='Adicione Area del Proyecto.')],
          label ='Detalles de Confidencialidad',
          represent=lambda v, r: 'N/A' if v is None else v),
    Field('status','string',
          label='Estado De Pasantia',
          represent=lambda v, r: 'N/A' if v is None else v),
    Field('etapa','reference Etapa',
          requires=IS_IN_DB(db, db.Etapa, '%(nombre)s',
          error_message='Elija una de las Etapas.'),
          label='Etapa (*)'),
    Field('fecha_creacion','datetime',default=datetime.now(),
          represent=lambda v, r: 'N/A' if v is None else v),
    Field('fecha_inicio','string',
          label='Fecha de inicio',
          represent=lambda v, r: 'N/A' if v is None else v),
    Field('fecha_fin','string',
          label='Fecha de culminacion',
          represent=lambda v, r: 'N/A' if v is None else v),
    Field('fecha_tope_jurado','string',
          label='Fecha tope para designar jurado',
          represent=lambda v, r: 'N/A' if v is None else v),
    Field('fecha_defensa','string',
          label='Fecha de la defensa',
          represent=lambda v, r: 'N/A' if v is None else v)
)
