# -*- coding: utf-8 -*-
from gluon import *
def Pais_Table(db,T):
    db.define_table('Pais',
        Field('first_name','string'),
        Field('ddi', 'string'),
        format='%(first_name)s')

    if db(db.Pais.id > 0).count() == 0:
        db.Pais.insert(
            first_name='Venezuela',
            ddi='',
        )
        db.Pais.insert(
            first_name='Estados Unidos'
        )
        db.Pais.insert(
            first_name='Afganistán'
        )
        db.Pais.insert(
            first_name='Albania'
        )
        db.Pais.insert(
            first_name='Alemania'
        )
        db.Pais.insert(
            first_name='Andorra'
        )
        db.Pais.insert(
            first_name='Angola'
        )
        db.Pais.insert(
            first_name='Antigua y Barbuda'
        )
        db.Pais.insert(
            first_name='Arabia Saudita'
        )
        db.Pais.insert(
            first_name='Argelia'
        )
        db.Pais.insert(
            first_name='Argentina'
        )
        db.Pais.insert(
            first_name='Armenia'
        )
        db.Pais.insert(
            first_name='Albania'
        )
        db.Pais.insert(
            first_name='Australia'
        )
        db.Pais.insert(
            first_name='Austria'
        )
        db.Pais.insert(
            first_name='Azerbaiyán'
        )
        db.Pais.insert(
            first_name='Bahamas'
        )
        db.Pais.insert(
            first_name='Baréin'
        )
        db.Pais.insert(
            first_name='Bélgica'
        )
        db.Pais.insert(
            first_name='Belice'
        )
        db.Pais.insert(
            first_name='Bielorrusia'
        )
        db.Pais.insert(
            first_name='Birmania'
        )
        db.Pais.insert(
            first_name='Bolivia'
        )
        db.Pais.insert(
            first_name='Bosnia y Herzegovina'
        )
        db.Pais.insert(
            first_name='Botsuana'
        )
        db.Pais.insert(
            first_name='Brasil'
        )
        db.Pais.insert(
            first_name='Brunéi'
        )
        db.Pais.insert(
            first_name='Bulgaria'
        )
        db.Pais.insert(
            first_name='Burkina Faso'
        )
        db.Pais.insert(
            first_name='Burundi'
        )
        db.Pais.insert(
            first_name='Bután'
        )
        db.Pais.insert(
            first_name='Cabo Verde'
        )
        db.Pais.insert(
            first_name='Camboya'
        )
        db.Pais.insert(
            first_name='Camerún'
        )
        db.Pais.insert(
            first_name='Canadá'
        )
        db.Pais.insert(
            first_name='Catar'
        )
        db.Pais.insert(
            first_name='Chad'
        )
        db.Pais.insert(
            first_name='Chile'
        )
        db.Pais.insert(
            first_name='China'
        )
        db.Pais.insert(
            first_name='Chipre'
        )
        db.Pais.insert(
            first_name='Ciudad del Vaticano'
        )
        db.Pais.insert(
            first_name='Colombia'
        )
        db.Pais.insert(
            first_name='Comoras'
        )
        db.Pais.insert(
            first_name='Corea del Norte'
        )
        db.Pais.insert(
            first_name='Corea del Sur'
        )
        db.Pais.insert(
            first_name='Costa de Marfil'
        )
        db.Pais.insert(
            first_name='Costa Rica'
        )
        db.Pais.insert(
            first_name='Croacia'
        )
        db.Pais.insert(
            first_name='Cuba'
        )
        db.Pais.insert(
            first_name='Dinamarca'
        )
        db.Pais.insert(
            first_name='Dominica'
        )
        db.Pais.insert(
            first_name='Ecuador'
        )
        db.Pais.insert(
            first_name='Egipto'
        )
        db.Pais.insert(
            first_name='El Salvador'
        )
        db.Pais.insert(
            first_name='Emiratos Árabes Unidos'
        )
        db.Pais.insert(
            first_name='Eritrea'
        )
        db.Pais.insert(
            first_name='Eslovaquia'
        )
        db.Pais.insert(
            first_name='Eslovenia'
        )
        db.Pais.insert(
            first_name='España'
        )
        db.Pais.insert(
            first_name='Estonia'
        )
        db.Pais.insert(
            first_name='Etiopía'
        )
        db.Pais.insert(
            first_name='Filipinas'
        )
        db.Pais.insert(
            first_name='Finlandia'
        )
        db.Pais.insert(
            first_name='Fiyi'
        )
        db.Pais.insert(
            first_name='Francia'
        )
        db.Pais.insert(
            first_name='Gabón'
        )
        db.Pais.insert(
            first_name='Gambia'
        )
        db.Pais.insert(
            first_name='Georgia'
        )
        db.Pais.insert(
            first_name='Ghana'
        )
        db.Pais.insert(
            first_name='Granada'
        )
        db.Pais.insert(
            first_name='Grecia'
        )
        db.Pais.insert(
            first_name='Guatemala'
        )
        db.Pais.insert(
            first_name='Guyana'
        )
        db.Pais.insert(
            first_name='Guinea'
        )
        db.Pais.insert(
            first_name='Guinea-Bisáu'
        )
        db.Pais.insert(
            first_name='Guinea Ecuatorial'
        )
        db.Pais.insert(
            first_name='Haití'
        )
        db.Pais.insert(
            first_name='Honduras'
        )
        db.Pais.insert(
            first_name='Hungría'
        )
        db.Pais.insert(
            first_name='India'
        )
        db.Pais.insert(
            first_name='Indonesia'
        )
        db.Pais.insert(
            first_name='Irak'
        )
        db.Pais.insert(
            first_name='Irán'
        )
        db.Pais.insert(
            first_name='Irlanda'
        )
        db.Pais.insert(
            first_name='Islandia'
        )
        db.Pais.insert(
            first_name='Islas Marshall'
        )
        db.Pais.insert(
            first_name='Islas Salomón'
        )
        db.Pais.insert(
            first_name='Israel'
        )
        db.Pais.insert(
            first_name='Italia'
        )
        db.Pais.insert(
            first_name='Jamaica'
        )
        db.Pais.insert(
            first_name='Japón'
        )
        db.Pais.insert(
            first_name='Jordania'
        )
        db.Pais.insert(
            first_name='Kazajistán'
        )
        db.Pais.insert(
            first_name='Kenia'
        )
        db.Pais.insert(
            first_name='Kirguistán'
        )
        db.Pais.insert(
            first_name='Kiribati'
        )
        db.Pais.insert(
            first_name='Kuwait'
        )
        db.Pais.insert(
            first_name='Laos'
        )
        db.Pais.insert(
            first_name='Lesoto'
        )
        db.Pais.insert(
            first_name='Letonia'
        )
        db.Pais.insert(
            first_name='Líbano'
        )
        db.Pais.insert(
            first_name='Liberia'
        )
        db.Pais.insert(
            first_name='Libia'
        )
        db.Pais.insert(
            first_name='Liechtenstein'
        )
        db.Pais.insert(
            first_name='Lituania'
        )
        db.Pais.insert(
            first_name='Luxemburgo'
        )
        db.Pais.insert(
            first_name='Madagascar'
        )
        db.Pais.insert(
            first_name='Malasia'
        )
        db.Pais.insert(
            first_name='Malaui'
        )
        db.Pais.insert(
            first_name='Maldivas'
        )
        db.Pais.insert(
            first_name='Malí'
        )
        db.Pais.insert(
            first_name='Malta'
        )
        db.Pais.insert(
            first_name='Marruecos'
        )
        db.Pais.insert(
            first_name='Mauricio'
        )
        db.Pais.insert(
            first_name='Mauritania'
        )
        db.Pais.insert(
            first_name='México'
        )
        db.Pais.insert(
            first_name='Micronesia'
        )
        db.Pais.insert(
            first_name='Moldavia'
        )
        db.Pais.insert(
            first_name='Mónaco'
        )
        db.Pais.insert(
            first_name='Mongolia'
        )
        db.Pais.insert(
            first_name='Montenegro'
        )
        db.Pais.insert(
            first_name='Mozambique'
        )
        db.Pais.insert(
            first_name='Namibia'
        )
        db.Pais.insert(
            first_name='Nauru'
        )
        db.Pais.insert(
            first_name='Nepal'
        )
        db.Pais.insert(
            first_name='Nicaragua'
        )
        db.Pais.insert(
            first_name='Níger'
        )
        db.Pais.insert(
            first_name='Nigeria'
        )
        db.Pais.insert(
            first_name='Noruega'
        )
        db.Pais.insert(
            first_name='Nueva Zelanda'
        )
        db.Pais.insert(
            first_name='Omán'
        )
        db.Pais.insert(
            first_name='Países Bajos'
        )
        db.Pais.insert(
            first_name='Pakistán'
        )
        db.Pais.insert(
            first_name='Palaos'
        )
        db.Pais.insert(
            first_name='Panamá'
        )
        db.Pais.insert(
            first_name='Papúa Nueva Guinea'
        )
        db.Pais.insert(
            first_name='Paraguay'
        )
        db.Pais.insert(
            first_name='Perú'
        )
        db.Pais.insert(
            first_name='Polonia'
        )
        db.Pais.insert(
            first_name='Portugal'
        )
        db.Pais.insert(
            first_name='Reino Unido de Gran Bretaña e Irlanda del Norte'
        )
        db.Pais.insert(
            first_name='República Centroafricana'
        )
        db.Pais.insert(
            first_name='República Checa'
        )
        db.Pais.insert(
            first_name='República de Macedonia'
        )
        db.Pais.insert(
            first_name='República del Congo'
        )
        db.Pais.insert(
            first_name='República Democrática del Congo'
        )
        db.Pais.insert(
            first_name='República Dominicana'
        )
        db.Pais.insert(
            first_name='República Sudafricana'
        )
        db.Pais.insert(
            first_name='Ruanda'
        )
        db.Pais.insert(
            first_name='Rumanía'
        )
        db.Pais.insert(
            first_name='Rusia'
        )
        db.Pais.insert(
            first_name='Samoa'
        )
        db.Pais.insert(
            first_name='San Cristóbal y Nieves'
        )
        db.Pais.insert(
            first_name='San Marino'
        )
        db.Pais.insert(
            first_name='San Vicente y las Granadinas'
        )
        db.Pais.insert(
            first_name='Santa Lucía'
        )
        db.Pais.insert(
            first_name='Santo Tomé y Príncipe'
        )
        db.Pais.insert(
            first_name='Senegal'
        )
        db.Pais.insert(
            first_name='Serbia'
        )
        db.Pais.insert(
            first_name='Seychelles'
        )
        db.Pais.insert(
            first_name='Sierra Leona'
        )
        db.Pais.insert(
            first_name='Singapur'
        )
        db.Pais.insert(
            first_name='Siria'
        )
        db.Pais.insert(
            first_name='Somalia'
        )
        db.Pais.insert(
            first_name='Sri Lanka'
        )
        db.Pais.insert(
            first_name='Suazilandia'
        )
        db.Pais.insert(
            first_name='Sudán'
        )
        db.Pais.insert(
            first_name='Sudán del Sur'
        )
        db.Pais.insert(
            first_name='Suecia'
        )
        db.Pais.insert(
            first_name='Suiza'
        )
        db.Pais.insert(
            first_name='Surinam'
        )
        db.Pais.insert(
            first_name='Tailandia'
        )
        db.Pais.insert(
            first_name='Tanzania'
        )
        db.Pais.insert(
            first_name='Tayikistán'
        )
        db.Pais.insert(
            first_name='Timor Oriental'
        )
        db.Pais.insert(
            first_name='Togo'
        )
        db.Pais.insert(
            first_name='Tonga'
        )
        db.Pais.insert(
            first_name='Trinidad y Tobago'
        )
        db.Pais.insert(
            first_name='Túnez'
        )
        db.Pais.insert(
            first_name='Turkmenistán'
        )
        db.Pais.insert(
            first_name='Turquía'
        )
        db.Pais.insert(
            first_name='Tuvalu'
        )
        db.Pais.insert(
            first_name='Ucrania'
        )
        db.Pais.insert(
            first_name='Uganda'
        )
        db.Pais.insert(
            first_name='Uruguay'
        )
        db.Pais.insert(
            first_name='Uzbekistán'
        )
        db.Pais.insert(
            first_name='Vanuatu'
        )
        db.Pais.insert(
            first_name='Vietnam'
        )
        db.Pais.insert(
            first_name='Yemen'
        )
        db.Pais.insert(
            first_name='Yibuti'
        )
        db.Pais.insert(
            first_name='Zambia'
        )
        db.Pais.insert(
            first_name='Zimbabue'
        )
        db.commit()
