# -*- coding: utf-8 -*-

################################################################################
#                         INICIO DECLARACION BASE DE DATOS                     #
################################################################################

#------------------------------------------------------------------------------#
#                            MODULO DE INVENTARIO                              #
#------------------------------------------------------------------------------#
from gluon import *
def Accion_Usuario_Table(db,T):
    db.define_table('Accion_Usuario',
        Field('first_name'),
        Field('destino'),
        Field('contexto'),
        Field('rol','reference auth_group',
              requires=IS_IN_DB(db,'auth_group.id','%(role)s',zero=None),
              label='Roles (*)')
       )

    if db(db.Accion_Usuario.id > 0).count() == 0:
        db.Accion_Usuario.insert(
            first_name='Acciones',
            destino='/SPE/acciones_usuario/listar',
            contexto='coordinacion',
            rol='6'
        )
        db.Accion_Usuario.insert(
            first_name='Mis Pasantias',
            destino='/SPE/mis_pasantias/listar',
            contexto='coordinacion',
            rol='1'
        )
        db.Accion_Usuario.insert(
            first_name='Mis Permisos',
            destino='/SPE/mis_permisos/listar',
            contexto='coordinacion',
            rol='1'
        )
        db.Accion_Usuario.insert(
            first_name='Pasantias',
            destino='/SPE/pasantias/listar',
            contexto='pasantias',
            rol='6'
        )
        db.Accion_Usuario.insert(
            first_name='Pasantias',
            destino='/SPE/pasantias/listar',
            contexto=None,
            rol='3'
        )
        db.Accion_Usuario.insert(
            first_name='Editar Perfil',
            destino='/SPE/mi_perfil/configuracion',
            contexto='configuracion',
            rol='1'
        )
        db.Accion_Usuario.insert(
            first_name='Editar Curriculo',
            destino='/SPE/mi_perfil/editar_curriculo',
            contexto='configuracion',
            rol='1'
        )
        db.Accion_Usuario.insert(
            first_name='Usuarios',
            destino='/SPE/usuarios/listar',
            contexto='coordinacion',
            rol='6'
        )
        db.Accion_Usuario.insert(
            first_name='Usuarios',
            destino='/SPE/usuarios/listar',
            contexto='',
            rol='1'
        )
        db.Accion_Usuario.insert(
            first_name='Estudiantes',
            destino='/SPE/estudiantes/listar',
            contexto='coordinacion',
            rol='6'
        )
        db.Accion_Usuario.insert(
            first_name='Sedes',
            destino='/SPE/sedes/listar',
            contexto='catalogos',
            rol='6'
        )
        db.Accion_Usuario.insert(
            first_name='Carreras',
            destino='/SPE/carreras/listar',
            contexto='catalogos',
            rol='6'
        )
        db.Accion_Usuario.insert(
            first_name='coordinaciones',
            destino='/SPE/coordinaciones/listar',
            contexto='catalogos',
            rol='6'
        )
        db.Accion_Usuario.insert(
            first_name='Preinscripciones',
            destino='/SPE/preinscripciones/listar',
            contexto='pasantias',
            rol='6'
        )
        db.Accion_Usuario.insert(
            first_name='Colocaciones',
            destino='/SPE/colocaciones/listar',
            contexto='pasantias',
            rol='6'
        )
        db.Accion_Usuario.insert(
            first_name='Inscripciones',
            destino='/SPE/inscripciones/listar',
            contexto='pasantias',
            rol='6'
        )
        db.Accion_Usuario.insert(
            first_name='Planes De Trabajo',
            destino='/SPE/planes_trabajo/listar',
            contexto='pasantias',
            rol='6'
        )
        db.Accion_Usuario.insert(
            first_name='Mis Pasantias',
            destino='/SPE/Coordinador/consultarPasantias',
            contexto='coordinacion',
            rol='3'
        )
        db.Accion_Usuario.insert(
            first_name='Materias',
            destino='/SPE/materias/listar',
            contexto='',
            rol='1'
        )
        db.Accion_Usuario.insert(
            first_name='Materias',
            destino='/SPE/materias/listar',
            contexto='catalogos',
            rol='6'
        )
        db.Accion_Usuario.insert(
            first_name='Permisos',
            destino='/SPE/permisos/listar',
            contexto='pasantias',
            rol='6'
        )
        db.Accion_Usuario.insert(
            first_name='Permisos',
            destino='/SPE/permisos/agregar',
            contexto='pasantias',
            rol='1'
        )
        db.Accion_Usuario.insert(
            first_name='Permisos',
            destino='/SPE/permisos/listar',
            contexto='pasantias',
            rol='1'
        )
        db.Accion_Usuario.insert(
            first_name='Retiros',
            destino='/SPE/retiros/listar',
            contexto='pasantias',
            rol='6'
        )
        db.Accion_Usuario.insert(
            first_name='Roles',
            destino='/SPE/roles/listar',
            contexto='coordinacion',
            rol='6'
        )
        db.Accion_Usuario.insert(
            first_name='Asignar Roles',
            destino='/SPE/membresias/listar',
            contexto='coordinacion',
            rol='6'
        )
        db.Accion_Usuario.insert(
            first_name='Areas Laborales',
            destino='/SPE/areas_laborales/listar',
            contexto='catalogos',
            rol='6'
        )
        db.Accion_Usuario.insert(
            first_name='Configurar Accesos',
            destino='/SPE/accesos_etapa/listar',
            contexto='pasantias',
            rol='6'
        )
        db.Accion_Usuario.insert(
            first_name='Areas De Proyecto',
            destino='/SPE/areas_proyecto/listar',
            contexto='catalogos',
            rol='6'
        )
        db.Accion_Usuario.insert(
            first_name='Curriculos',
            destino='/SPE/curriculos/listar',
            contexto='pasantias',
            rol='6'
        )
        db.Accion_Usuario.insert(
            first_name='Etapas',
            destino='/SPE/etapas/listar',
            contexto='catalogos',
            rol='6'
        )
        db.Accion_Usuario.insert(
            first_name='Tipos De Documentos',
            destino='/SPE/tipos_documento/listar',
            contexto='catalogos',
            rol='6'
        )
        db.Accion_Usuario.insert(
            first_name='Categorias',
            destino='/SPE/categorias/listar',
            contexto='catalogos',
            rol='6'
        )
        db.Accion_Usuario.insert(
            first_name='Coordinadores',
            destino='/SPE/coordinadores/listar',
            contexto='coordinacion',
            rol='6'
        )
        db.Accion_Usuario.insert(
            first_name='Dedicaciones',
            destino='/SPE/dedicaciones/listar',
            contexto='catalogos',
            rol='6'
        )
        db.Accion_Usuario.insert(
            first_name='Departamentos',
            destino='/SPE/departamentos/listar',
            contexto='catalogos',
            rol='6'
        )
        db.Accion_Usuario.insert(
            first_name='Divisiones',
            destino='/SPE/divisiones/listar',
            contexto='catalogos',
            rol='6'
        )
        db.Accion_Usuario.insert(
            first_name='Ejecuciones',
            destino='/SPE/ejecuciones/listar',
            contexto='pasantias',
            rol='6'
        )
        db.Accion_Usuario.insert(
            first_name='Empresas',
            destino='/SPE/empresas/listar',
            contexto='coordinacion',
            rol='6'
        )
        db.Accion_Usuario.insert(
            first_name='Estados',
            destino='/SPE/estados/listar',
            contexto='catalogos',
            rol='6'
        )
        db.Accion_Usuario.insert(
            first_name='Materias Periodo',
            destino='/SPE/materias_periodo/listar',
            contexto='coordinacion',
            rol='6'
        )
        db.Accion_Usuario.insert(
            first_name='Paises',
            destino='/SPE/paises/listar',
            contexto='catalogos',
            rol='6'
        )
        db.Accion_Usuario.insert(
            first_name='Periodos',
            destino='/SPE/periodos/listar',
            contexto='catalogos',
            rol='6'
        )
        db.Accion_Usuario.insert(
            first_name='Profesores',
            destino='/SPE/profesores/listar',
            contexto='coordinacion',
            rol='6'
        )
        db.Accion_Usuario.insert(
            first_name='Tutores Industriales',
            destino='/SPE/tutores_industriales/listar',
            contexto='coordinacion',
            rol='6'
        )
        db.Accion_Usuario.insert(
            first_name='Universidades',
            destino='/SPE/universidades/listar',
            contexto='catalogos',
            rol='6'
        )
        db.Accion_Usuario.insert(
            first_name='Personal Administrativo',
            destino='/SPE/administrativos/listar',
            contexto='coordinacion',
            rol='6'
        )
        db.commit()

#------------------------------------------------------------------------------#

################################################################################
#                          FIN DECLARACION BASE DE DATOS                       #
################################################################################
