# -*- coding: utf-8 -*-
from gluon import *
from datetime import datetime
def Pasantia(db,T):
    db.define_table('Pasantia',
        Field('titulo',
               label='Titulo'),
        Field('estudiante','reference Estudiante',
              label='Estudiante (*)'),
        Field('tutor_academico','reference Profesor',
              label='Tutor Academico (*)'),
        Field('tutor_industrial','reference Tutor_Industrial',
              label='Tutor Industrial (*)'),
        Field('periodo','reference Periodo',
              label='Periodo (*)'),
        Field('area_proyecto','reference Area_Proyecto',
              label='Areas de Proyectos (*)'),
        Field('resumen_proyecto','text',
              label ='Resumen del Proyecto',
              represent=lambda v, r: 'N/A' if v is None else v),
        Field('materia','reference Materia',
              label='Materia (*)'),
        Field('objetivo',
              label ='Objetivo General',
              represent=lambda v, r: 'N/A' if v is None else v),
        Field('confidencialidad',
              requires=[IS_NOT_EMPTY
                            (error_message='Adicione Area del Proyecto.')],
              label ='Detalles de Confidencialidad',
              represent=lambda v, r: 'N/A' if v is None else v),
        Field('status','string',
              label='Estado De Pasantia',
              represent=lambda v, r: 'N/A' if v is None else v),
        Field('etapa','reference Etapa',
              label='Etapa (*)'),
        Field('fecha_creacion','datetime',default=datetime.now(),
              represent=lambda v, r: 'N/A' if v is None else v),
        Field('fecha_inicio','date',
              label='Fecha de inicio',
              represent=lambda v, r: 'N/A' if v is None else v),
        Field('fecha_fin','date',
              label='Fecha de culminacion',
              represent=lambda v, r: 'N/A' if v is None else v),
        Field('fecha_tope_jurado','date',
              label='Fecha tope para designar jurado',
              represent=lambda v, r: 'N/A' if v is None else v),
        Field('fecha_defensa','date',
              label='Fecha de la defensa',
              represent=lambda v, r: 'N/A' if v is None else v),
        format=lambda r: '%s %s - %s %s (%s)' % (r.id,r.titulo, r.estudiante.nombre,r.estudiante.apellido,r.estudiante.usbid)
    )
