db.define_table('Coordinador',
    Field('usuario',
          requires=IS_IN_DB(db, db.UsuarioUSB, '%(usbid)s',
          error_message='Elija uno de los usuarios.'),
          label='Usuario (*)'),
    Field('carnet',
          requires=IS_MATCH('^\d{2}?[\s.-]?\d{5}$',
                        error_message='Introduzca un carnet valido.'),
          label='Carnet'),
    Field('coordinacion',
          requires=IS_IN_DB(db, db.Coordinacion, '%(nombre)s',
          error_message='Elija una de las coordinaciones.'),
          label='Coordinacion (*)'),
    Field('correo_Alternativo',  requires=IS_EMAIL(error_message='Introduzca un email valido.'),
          label='Correo Alternativo'))