db.define_table('Profesor',
       Field('usuario',
          requires=IS_IN_DB(db, db.UsuarioUSB, '%(usbid)s',
          error_message='Elija uno de los usuarios.'),
          label='Usuario (*)'),
    Field('categoria','reference Categoria',
          requires=IS_IN_DB(db, db.Categoria, '%(nombre)s',
          error_message='Elija una de las categoria.'),
          label='Categoria (*)'),
    Field('dedicacion','reference Dedicacion',
          requires=IS_IN_DB(db, db.Dedicacion, '%(nombre)s',
          error_message='Elija una de las dedicaciones.'),
          label='Dedicacion (*)'),
    Field('departamento','reference Departamento',
          requires=IS_IN_DB(db, db.Departamento, '%(nombre)s',
          error_message='Elija uno de los departamentos.'),
          label='Departamento (*)'),
    Field('sede','reference Sede',
          requires=IS_IN_DB(db, db.Sede, '%(nombre)s',
          error_message='Elija una de las sedes.'),
          label='Sede (*)'),
    Field('activo','boolean')
)