db.define_table('Estudiante',
    Field('usuario',
          requires=IS_IN_DB(db, db.UsuarioUSB, '%(usbid)s',
          error_message='Elija uno de los usuarios.'),
          label='Usuario (*)'),
    Field('carnet',
          requires=IS_MATCH('^\d{2}?[\s.-]?\d{5}$',
                        error_message='Introduzca un carnet valido.'),
          label='Carnet'),
    Field('carrera', 'reference Carrera',
          label='Carrera'),
    Field('sede','reference Sede',
          requires=IS_IN_DB(db, db.Sede, '%(nombre)s',
          error_message='Elija una de las sedes.'),
          label='Sede (*)'),
    Field('activo','boolean')
    )